[package]
name = "ai_playlist"
version = "0.0.1"
edition = "2021"

[dependencies]
anyhow.workspace = true
sqlx.workspace = true

subd-macros = { path = "../subd-macros/" }
subd-db = { path = "../subd-db/" }
uuid.workspace = true

[dev-dependencies]

tokio.workspace = true
